### ISSUE TITLE
API not implemented properly

### ISSUE THREAD

**Issue by JPANv2** [spacechase0/SpaceCore_SDV#8]
While there is an API interface and an API.cs file, that API is never exposed over SMAPI, by implementing the GetAPI function in the mod. This makes retrieving custom skills impossible.

Also, a feature request: Could you add to the API a method to get the Profession ID for custom skill professions, based on name or otherwise?

**Comment by spacechase0** [comment]
Just now saw this. I realize I'm a "bit" late. Sorry about that. I must have missed the email.

I just commited the fix. I'll push it shortly.
